feat: update contact input fields to solid white background and forest green text
Last login: Sat May 16 21:21:39 on ttys000
Error while loading conda entry point: conda-libmamba-solver (dlopen(/opt/anaconda3/lib/python3.12/site-packages/libmambapy/bindings.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.20.dylib
  Referenced from: <496442DC-0EDE-3705-A2B5-401A4FC0D733> /opt/anaconda3/lib/libmamba.2.0.0.dylib
  Reason: tried: '/opt/anaconda3/lib/libarchive.20.dylib' (no such file), '/opt/anaconda3/lib/python3.12/site-packages/libmambapy/../../../libarchive.20.dylib' (no such file), '/opt/anaconda3/lib/python3.12/site-packages/libmambapy/../../../libarchive.20.dylib' (no such file), '/opt/anaconda3/bin/../lib/libarchive.20.dylib' (no such file), '/opt/anaconda3/bin/../lib/libarchive.20.dylib' (no such file), '/usr/local/lib/libarchive.20.dylib' (no such file), '/usr/lib/libarchive.20.dylib' (no such file, not in dyld cache))
(base) afaaqs@Annas-MacBook-Pro-5 ~ % git status
fatal: not a git repository (or any of the parent directories): .git
(base) afaaqs@Annas-MacBook-Pro-5 ~ % streamlit run app.py
Usage: streamlit run [OPTIONS] [TARGET] [ARGS]...
Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: app.py
(base) afaaqs@Annas-MacBook-Pro-5 ~ % git status
fatal: not a git repository (or any of the parent directories): .git
(base) afaaqs@Annas-MacBook-Pro-5 ~ % cd ophia-dashboard
(base) afaaqs@Annas-MacBook-Pro-5 ophia-dashboard % source venv/bin/activate
(venv) (base) afaaqs@Annas-MacBook-Pro-5 ophia-dashboard % git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   app.py

no changes added to commit (use "git add" and/or "git commit -a")
(venv) (base) afaaqs@Annas-MacBook-Pro-5 ophia-dashboard % git add app.py
(venv) (base) afaaqs@Annas-MacBook-Pro-5 ophia-dashboard % git commit -m "feat: update contact input fields to solid white background and forest green text"
[main fb9ce56] feat: update contact input fields to solid white background and forest green text
 1 file changed, 797 insertions(+), 252 deletions(-)
(venv) (base) afaaqs@Annas-MacBook-Pro-5 ophia-dashboard % git push origin main
To https://github.com/fthanifa/OPHIA-GDG.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/fthanifa/OPHIA-GDG.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(venv) (base) afaaqs@Annas-MacBook-Pro-5 ophia-dashboard % git pull origin main --rebase
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 13 (delta 5), reused 3 (delta 1), pack-reused 0 (from 0)
Unpacking objects: 100% (13/13), 8.59 KiB | 517.00 KiB/s, done.
From https://github.com/fthanifa/OPHIA-GDG
 * branch            main       -> FETCH_HEAD
   85be3ff..43960be  main       -> origin/main
CONFLICT (modify/delete): app.py deleted in HEAD and modified in fb9ce56 (feat: update contact input fields to solid white background and forest green text).  Version fb9ce56 (feat: update contact input fields to solid white background and forest green text) of app.py left in tree.
error: could not apply fb9ce56... feat: update contact input fields to solid white background and forest green text
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply fb9ce56... feat: update contact input fields to solid white background and forest green text
(venv) (base) afaaqs@Annas-MacBook-Pro-5 ophia-dashboard % git push origin main
To https://github.com/fthanifa/OPHIA-GDG.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/fthanifa/OPHIA-GDG.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(venv) (base) afaaqs@Annas-MacBook-Pro-5 ophia-dashboard % git add app.py
(venv) (base) afaaqs@Annas-MacBook-Pro-5 ophia-dashboard % git rebase --continue
hint: Waiting for your editor to close the file...
feat: update contact input fields to solid white background and forest green text

~
~
~
~
"~/ophia-dashboard/.git/COMMIT_EDITMSG" 17L, 568B
:wq#